export interface MariageInterface {
    nomTemoinHomme: string;
    prenomsTemoinHomme: string;
    professionTemoinHomme: string;
    datenaissTemoinHomme: string;
    lieunaissTemoinHomme: string;
    adresseTemoinHomme: string;
    nomTemoinFemme: string;
    prenomsTemoinFemme: string;
    professionTemoinFemme: string;
    datenaissTemoinFemme: string;
    lieunaissTemoinFemme: string;
    adresseTemoinFemme: string;
    description: string;
    numeroCopieMariage: string;
    dateMariage: string;
    heureMariage: string;
    idMaire: string;
    nationaliteHomme: string;
    idPremierCopieHomme: any;
    nomHomme: string;
    prenomsHomme: string;
    professionHomme: string;
    dateNaissHomme: string;
    lieuNaissHomme: string;
    adresseHomme: string;
    typeHomme: string;
    idPereHomme: number;
    nomPereHomme: string;
    prenomsPereHomme: string;
    dateNaissPereHomme: string;
    lieuNaissPereHomme: string;
    professionPereHomme: string;
    adressePereHomme: string;
    idMereHomme: number;
    nomMereHomme: string;
    prenomsMereHomme: string;
    dateNaissMereHomme: string;
    lieuNaissMereHomme: string;
    professionMereHomme: string;
    adresseMereHomme: string;
    idPremierCopieFemme: string;
    nationaliteFemme: string;
    nomFemme: string;
    prenomsFemme: string;
    professionFemme: string;
    dateNaissFemme: string;
    lieuNaissFemme: string;
    adresseFemme: string;
    idPereFemme: number;
    nomPereFemme: string;
    prenomsPereFemme: string;
    dateNaissPereFemme: string;
    lieuNaissPereFemme: string;
    professionPereFemme: string;
    adressePereFemme: string;
    idMereFemme: number;
    nomMereFemme: string;
    prenomsMereFemme: string;
    dateNaissMereFemme: string;
    lieuNaissMereFemme: string;
    professionMereFemme: string;
    adresseMereFemme: string;
}
export interface MaireInterface{
    idMaire: string;
    nomMaire:string;
    prenomsMaire:string;
    fonction:string;
}
export interface MariageInterfaceInterneInterne{
        nomTemoinHomme:string;
        prenomsTemoinHomme: string;
        professionTemoinHomme: string;
        datenaissTemoinHomme: string;
        lieunaissTemoinHomme: string;
        adresseTemoinHomme: string;
        nomTemoinFemme: string;
        prenomsTemoinFemme: string;
        professionTemoinFemme: string;
        datenaissTemoinFemme: string;
        lieunaissTemoinFemme: string;
        adresseTemoinFemme: string;
        description:string;
        numeroCopieMariage: string;
        dateMariage: string;
        heureMariage: string;
        idMaire: string;
        idPremierCopieHomme: any;
        idPremierCopieFemme: string;
}

export interface MariageInterfaceInterneExterne{
    nomTemoinHomme: string;
    prenomsTemoinHomme: string;
    professionTemoinHomme: string;
    datenaissTemoinHomme: string;
    lieunaissTemoinHomme: string;
    adresseTemoinHomme: string;
    nomTemoinFemme: string;
    prenomsTemoinFemme: string;
    professionTemoinFemme: string;
    datenaissTemoinFemme: string;
    lieunaissTemoinFemme: string;
    adresseTemoinFemme: string;
    description: string;
    numeroCopieMariage: string;
    dateMariage: string;
    heureMariage: string;
    idMaire: string;
    idPremierCopieHomme: string;
    nationaliteFemme: string;
    nomFemme: string;
    prenomsFemme: string;
    professionFemme: string;
    dateNaissFemme: string;
    lieuNaissFemme: string;
    adresseFemme: string;
    typeFemme: string;
    nomPereFemme: string;
    prenomsPereFemme: string;
    dateNaissPereFemme: string;
    lieuNaissPereFemme: string;
    professionPereFemme: string;
    adressePereFemme: string;
    nomMereFemme: string;
    prenomsMereFemme: string;
    dateNaissMereFemme: string;
    lieuNaissMereFemme: string;
    professionMereFemme: string;
    adresseMereFemme: string;
}

export interface MariageInterfaceExterneInterne{
    nomTemoinHomme: string;
    prenomsTemoinHomme: string;
    professionTemoinHomme: string;
    datenaissTemoinHomme: string;
    lieunaissTemoinHomme: string;
    adresseTemoinHomme: string;
    nomTemoinFemme: string;
    prenomsTemoinFemme: string;
    professionTemoinFemme: string;
    datenaissTemoinFemme: string;
    lieunaissTemoinFemme: string;
    adresseTemoinFemme: string;
    description: string;
    numeroCopieMariage: string;
    dateMariage: string;
    heureMariage: string;
    idMaire: string;
    idPremierCopieFemme: string;
    nationaliteHomme: string;
    nomHomme: string;
    prenomsHomme: string;
    professionHomme: string;
    dateNaissHomme: string;
    lieuNaissHomme: string;
    adresseHomme: string;
    nomPereHomme: string;
    prenomsPereHomme: string;
    dateNaissPereHomme: string;
    lieuNaissPereHomme: string;
    professionPereHomme: string;
    adressePereHomme: string;
    nomMereHomme: string;
    prenomsMereHomme: string;
    dateNaissMereHomme: string;
    lieuNaissMereHomme: string;
    professionMereHomme: string;
    adresseMereHomme: string;
}
  